# Generated by Django 4.0.2 on 2022-03-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpool',
            name='creation_date',
        ),
    ]
